---

- name: Create user
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{ user }}"
        state: present
      become: true
      register: out
    - ansible.builtin.debug:
        var: out