
    - name: Install mysql
      ansible.builtin.apt:
        name: mysql-server
        state: latest
        update_cache: true

    - name: Install pymysql
      ansible.builtin.apt:
        name: "python3-mysqldb"
        state: latest      

    - name: Setup root user
      community.mysql.mysql_user:
        name: "root"
        password: "password"
        login_user: root
        login_password: password
        check_implicit_admin: true
        login_unix_socket: "/var/run/mysqld/mysqld.sock"

    - name: Remove anonymous user
      community.mysql.mysql_user:
        name: ""
        state: absent
        login_user: root
        login_password: password
        
    - name: Remove test db
      community.mysql.mysql_db:
        name: "test"
        state: absent
        login_user: root
        login_password: password