---

- name: Apply auth configuration to all nodes
  hosts: all
  become: yes
  strategy: free

  roles:
    - { role: init/debian, when: ansible_os_family == 'Debian' }
#    - { role: INIT/RHEL, when: ansible_os_family == 'RedHat' }
#    - { role: INIT/Gentoo, when: ansible_os_family == 'Gentoo' }
