
---

- name: Install LEMP stack
  hosts: all
  become: yes
  strategy: free

  roles:
  - roles/nginx
  - roles/mysql
  - roles/php

  tasks:
  - name: "Restart nginx"
    ansible.builtin.service:
      name: nginx
      state: "restarted"   


