
---

- name: Install nginx
  hosts: webservers
  become: yes
  strategy: free

  roles:
  - roles/nginx

  tasks:
  - name: "Restart nginx"
    ansible.builtin.service:
      name: nginx
      state: "restarted"   


