---

- name: Setup root password
  user:
    name: root
    state: present
    password: "!"

#- name: Add ansible user group
#  group:
#    name: ansible
#    state: present

#- name: Add ansible user
#  user:
#    name: ansible
#    state: present
#    comment: "Ansible user"
#    group: ansible
#    password: !
#    shell: /bin/bash

- name: Add ansible key
  ansible.posix.authorized_key:
    user: kac
    state: present
#    exclusive: no
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCz7K/Uh6SetBfAxKY643+cQTxjM3T81jBH2VC+fF1IgxWp5FSrhVaQhcJKmJoU7qgniIJczbflhpKUz5qrJJfdAzFR+r9AE47BLL03D24gh7K5RD5q8ER0dW384aJTTAbqVpOpq2/pKsRKRUUJceY1vzy6KBFzUlmK8bXlu4pvdneFLyb6RM9HRYibDhZTwxxdgQEQOQxsEu961v+Y70u5zXqWztk5r3bb5WZ32SoJh9ewYLf0fUJqNeX5P8XyFXmUqCPiPzhekRY2We57GgASE/O9KbvTIudAQh+iTpZtHWL9qO2u+M0p4dQqEZ7xjDkCJJtBqwLVvDkkRMJ/pJzcx1fH21O9+F8sBHNNZn1EOyBO0APDwbvRGG4VUHmUIGYexmZeylWnncZHREzo6F0DQ27pPJUfjh2EZwHPMfIGqY5G1e/VziQGe60Rm/tztlovfmWWx4hkHIlwwHucAEmCOGHlq5EOhZE7gqa+E5yPd0uXpAvmxGazRLRjR67KgP0= kac@kac"

- name: Disable Root Login in sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin No'
  notify:
    - restart ssh

- name: Create sudo configuration
  template:
    src: sudoers_debian.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
