---

- name: Configure webserver with nginx
  hosts: webservers
  become: true
  
  tasks:
    - name: Update package cache
      package:
        name: nginx
        state: latest
        update_cache: true

    - name: Copy nginx files
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/sites-available/default
#      notify:
#        - reload nginx

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default

    - name: Create index config
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
#      notify:
#        - reload nginx


